---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.7
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[microfocus_test]
    attributes:
      microfocus:
        server_express:
          checksum: <%= ENV['MICROFOCUS_SERVER_EXPRESS_CHECKSUM'] %>
          license_number: <%= ENV['MICROFOCUS_SERVER_EXPRESS_LICENSE_NUMBER'] %>
          serial_number: <%= ENV['MICROFOCUS_SERVER_EXPRESS_SERIAL_NUMBER'] %>
          url: <%= ENV['MICROFOCUS_SERVER_EXPRESS_URL'] %>
