---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: server_express
    run_list:
      - recipe[microfocus_test::server_express]
    attributes:
      microfocus:
        server_express:
          checksum: <%= ENV['MICROFOCUS_SERVER_EXPRESS_CHECKSUM'] %>
          license_number: <%= ENV['MICROFOCUS_SERVER_EXPRESS_LICENSE_NUMBER'] %>
          serial_number: <%= ENV['MICROFOCUS_SERVER_EXPRESS_SERIAL_NUMBER'] %>
          url: <%= ENV['MICROFOCUS_SERVER_EXPRESS_URL'] %>
          version: 5.1wp11
  - name: visual_cobol
    run_list:
      - recipe[microfocus_test::visual_cobol]
    attributes:
      microfocus:
        visual_cobol:
          visual_cobol_checksum: <%= ENV['MICROFOCUS_VISUAL_COBOL_CHECKSUM'] %>
          visual_cobol_url: <%= ENV['MICROFOCUS_VISUAL_COBOL_URL'] %>
          visual_cobol_license_checksum: <%= ENV['MICROFOCUS_VISUAL_COBOL_LICENSE_CHECKSUM'] %>
          visual_cobol_license_url: <%= ENV['MICROFOCUS_VISUAL_COBOL_LICENSE_URL'] %>
